services:
  - type: web
    name: fabric-trend-spotter
    runtime: python
    plan: free
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: ETSY_API_KEY
        sync: false
      - key: ECONOMIC_APP_SECRET
        sync: false
      - key: ECONOMIC_GRANT_TOKEN
        sync: false
      - key: WOOCOMMERCE_URL
        sync: false
      - key: WOOCOMMERCE_KEY
        sync: false
      - key: WOOCOMMERCE_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
