services:
  - type: web
    name: fabric-trend-spotter
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: ETSY_API_KEY
        sync: false
